name: Build

on:
  pull_request:
jobs:
  savepr:
    runs-on: ubuntu-latest
    name: Save PR number if running on PR by dependabot
    steps:
      - name: Create Directory and save issue
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }}
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        name: Upload artifact
        with:
          name: pr
          path: pr/
